# Use Node.js for development
FROM node:lts AS dev

RUN npm install -g pnpm

WORKDIR /app
COPY package*.json ./
RUN pnpm install
COPY . .

# Expose the development port
EXPOSE 3000

# Run Next.js in development mode
CMD ["npm", "run", "dev"]
